### PR TITLE
add combineMAlignments func

### PR DESCRIPTION
**Pull request by biobenkj**
This adds functionality to combine MAlignments objects and add it into the MAlignmentsList object on the fly. There is some other hidden functions to make sure that the cache is fixed for the metadata of the merged object when putting it all back together. *Needs review.* @ttriche @heoly32

### CODE REVIEW

**Comment by biobenkj** [comment]
Now that I'm thinking about this a little more, it might be useful to take some of the hidden/helper functions and turn them into utility functions for adding and removing samples from the MAlignmentsList object while keeping the metadata in sync. This turns out to not be quite as trivial as one might think. Thoughts?

**Comment by ttriche** [comment]
Have wondered about this for a while. VRanges are super useful but also quirky. Likewise gmapR vs pileup (the latter works on GAlignments/MAlignments, with or without concatenation, while the former does not).

--t

On Feb 28, 2019, at 8:34 AM, Ben Johnson <notifications@github.com<mailto:notifications@github.com>> wrote:


Now that I'm thinking about this a little more, it might be useful to take some of the hidden/helper functions and turn them into utility functions for adding and removing samples from the MAlignmentsList object while keeping the metadata in sync. This turns out to not be quite as trivial as one might think. Thoughts?

**Comment by biobenkj** [comment]
Hm. Well this sounds like we are hurtling towards needing to switch over to pileup. @heoly32 is this something we can try and hammer away at?

Also, @ttriche okay to merge this on the git dev branch? I know that the cleaning helper function is redundant with validMetadata but can switch over when we build out the other utility functions.

**Comment by ttriche** [comment]
go for it

Timothy J. Triche, Jr., PhD
Assistant Professor of Bioinformatics
Van Andel Research Institute
333 Bostwick Avenue NE
Grand Rapids, MI, 49503
(616) 234-5316 (office)
(626) 375-9663 (mobile)
(616) 234-5377 (administrative, courtesy of Christie Preston)
trichelab.vai.org

________________________________________

**Pull request merged**
